name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  # Event `pull_request`: Compare the last commit of the main branch or last remote commit of the PR branch -> to the current commit of a PR branch.
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      # -----------------------------------------------------------------------------------------------------------
      # Example 4
      # -----------------------------------------------------------------------------------------------------------
      - name: Get all test, doc and src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files_yaml: |
            doc1:
              - 'README.md'
            doc2:
              - '.github/workflows/checkModified.yml'
          # Optionally set `files_yaml_from_source_file` to read the YAML from a file. e.g `files_yaml_from_source_file: .github/changed-files.yml`

      - name: Run step if test file(s) change
        # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
        if: steps.changed-files-yaml.outputs.doc1_any_changed == 'true'  
        env:
          DOC1_ALL_CHANGED_FILES: ${{ steps.changed-files-yaml.outputs.doc1_all_changed_files }}
          DOC2_ALL_CHANGED_FILES: ${{ steps.changed-files-yaml.outputs.doc2_all_changed_files }}
        run: |
          echo ""
          echo "List all the files that have changed: $DOC1_ALL_CHANGED_FILES"
          echo ""
          echo "List all the files that have changed: $DOC2_ALL_CHANGED_FILES"
          if [ $DOC1_ALL_CHANGED_FILES == "" ]; then
            echo "README.md Not Modified"
          fi
          if [ $DOC2_ALL_CHANGED_FILES == "" ]; then
            echo "checkModified.yml Not Modified"
          fi
          
      
