on:
  schedule:
    - cron: '45 23 * * *'

jobs:
  deploy:
    name: Review reminders
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: blombard/review-reminder@v0.7
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        reminder-comment: "Don't forget to review this PR asap !"
        days-before-reminder: '1'
